name = "nsu-doc-editor-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
GITHUB_APP_ID = "3338741"
GITHUB_INSTALLATION_ID = "146793812"
GH_OWNER = "nsuok-programmers"
DOCS_REPO = "nsu-prod-docs"
ALLOWED_ORIGIN = "https://nsuok-programmers.github.io"
